// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/promptloop-redesign/RedesignedHome.tsx": () => import("../components/mockups/promptloop-redesign/RedesignedHome.tsx")
};
