// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/ClarityFirst.tsx": () => import("../components/mockups/hero-variants/ClarityFirst.tsx"),
  "./components/mockups/hero-variants/ScoreEverything.tsx": () => import("../components/mockups/hero-variants/ScoreEverything.tsx"),
  "./components/mockups/hero-variants/ShowTheSteps.tsx": () => import("../components/mockups/hero-variants/ShowTheSteps.tsx"),
  "./components/mockups/promptloop-redesign/RedesignedHome.tsx": () => import("../components/mockups/promptloop-redesign/RedesignedHome.tsx")
};
