// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/inspo-designs/ElevenLabsStyle.tsx": () => import("../components/mockups/inspo-designs/ElevenLabsStyle.tsx"),
  "./components/mockups/inspo-designs/LinearStyle.tsx": () => import("../components/mockups/inspo-designs/LinearStyle.tsx"),
  "./components/mockups/inspo-designs/NotionStyle.tsx": () => import("../components/mockups/inspo-designs/NotionStyle.tsx"),
  "./components/mockups/inspo-designs/PerplexityStyle.tsx": () => import("../components/mockups/inspo-designs/PerplexityStyle.tsx"),
  "./components/mockups/inspo-designs/StripeStyle.tsx": () => import("../components/mockups/inspo-designs/StripeStyle.tsx"),
  "./components/mockups/inspo-designs/VercelStyle.tsx": () => import("../components/mockups/inspo-designs/VercelStyle.tsx"),
  "./components/mockups/promptloop-redesign/RedesignedHome.tsx": () => import("../components/mockups/promptloop-redesign/RedesignedHome.tsx"),
  "./components/mockups/hero-variants/ClarityFirst.tsx": () => import("../components/mockups/hero-variants/ClarityFirst.tsx"),
  "./components/mockups/hero-variants/ScoreEverything.tsx": () => import("../components/mockups/hero-variants/ScoreEverything.tsx"),
  "./components/mockups/hero-variants/ShowTheSteps.tsx": () => import("../components/mockups/hero-variants/ShowTheSteps.tsx")
};
